services:
  api:
    build: ./api
    ports: 
      - 5000:5000
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  front-end:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
