services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./.default.conf:/etc/nginx/conf.d/default.conf
  api:
    build: ./api
    ports: 
      - 5000:5000
      - 9229:9229
    volumes:
      - ./api:/usr/src/app
    command: npm run dev
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  front-end:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
